{% set name = "EMD-signal" %}
{% set version = "1.7.0" %}

package:
  name: emd-signal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emd_signal-{{ version }}.tar.gz
  sha256: cf72c65f32ebeb954bb4dc49b52db187e8289a284b3b0710c12c0200a17d2cb9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=58
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.12
    - scipy >=0.19
    - pathos >=0.2.1
    - tqdm <5.0,>=4.64.0

test:
  imports:
    - PyEMD
    - PyEMD.tests.test_all
  commands:
    - pip check
    - python -m "PyEMD.tests.test_all"
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/laszukdawid/PyEMD
  summary: Implementation of the Empirical Mode Decomposition (EMD) and its variations
  license: Apache-2.0
  license_file: LICENSE.md
  license_family: Apache
  license_url: https://github.com/laszukdawid/PyEMD/blob/master/LICENSE.md
  dev_url: https://github.com/laszukdawid/PyEMD
  doc_url: https://pyemd.readthedocs.org/
  doc_source_url: https://github.com/laszukdawid/PyEMD/blob/master/doc/

extra:
  recipe-maintainers:
    - pedroaugustosmribeiro
